import json

keywords={
  "phishing_keywords": [
    "disabled permanently",
    "blocked",
    "account blocked",
    "suspicious activity",
    "unusual activity",
    "verify your account",
    "urgent action required",
    "confirm your identity",
    "account verification",
    "security alert",
    "login attempt",
    "unauthorized access",
    "identity verification",
    "account review",
    "account restriction",
    "unusual login",
    "login from new location",
    "security measure",
    "validate your account",
    "account validation",
    "account suspension",
    "confirm your account",
    "confirm your email",
    "verify your email",
    "reset your password",
    "change your password",
    "your account is compromised",
    "account security",
    "login security",
    "update your information",
    "phishing attempt",
    "phishing alert",
    "account compromised",
    "fraud alert",
    "urgent response required",
    "limited time offer",
    "action required",
    "verify information",
    "click the link below",
    "click here to verify",
    "click to confirm",
    "verify now",
    "secure your account",
    "identity theft",
    "verify your identity",
    "identity confirmation",
    "unauthorized transaction",
    "suspicious transaction",
    "login verification",
    "account confirmation",
    "change of password",
    "change your login",
    "reset account",
    "unusual sign-in",
    "unauthorized login",
    "verify your login",
    "reset your login",
    "unauthorized user",
    "login verification",
    "security check",
    "security update",
    "security alert",
    "verify your email address",
    "verify your identity",
    "verify your information",
    "security breach",
    "fraudulent activity",
    "phishing link",
    "your account is at risk",
    "your account has been compromised",
    "update your security",
    "update your password",
    "verify your credentials",
    "account termination",
    "your account will be closed",
    "your account will be suspended",
    "your account will be blocked",
    "your account is in danger",
    "urgent security notice",
    "verify your login credentials",
    "login validation",
    "security validation",
    "unauthorized access detected",
    "unusual sign-in activity",
    "your account has been flagged",
    "login security alert",
    "account security notice",
    "verify your account details",
    "confirm your login",
    "account lockdown",
    "security confirmation",
    "confirm your account activity",
    "login validation required",
    "suspicious login attempt",
    "account breach",
    "verify your security",
    "confirm your access",
    "account termination",
    "your account is suspended",
    "urgent account update",
    "your account is at risk",
    "account verification required",
    "click the link to verify",
    "urgent account notification",
    "account confirmation required",
    "validate your account",
    "validate your login",
    "confirm your email address",
    "account compromise alert",
    "unauthorized login detected",
    "suspicious login activity",
    "your account is compromised",
    "verify your credit card",
    "update your credit card",
    "account information verification",
    "account login verification",
    "suspicious activity on your account",
    "account security update",
    "verify your account activity",
    "confirm your login credentials",
    "security validation required",
    "unauthorized access to your account",
    "verify your account security",
    "suspicious login attempt",
    "phishing website detected",
    "your account is being reviewed",
    "urgent account validation",
    "confirm your personal information",
    "update your account details",
    "account suspension notice",
    "security breach detected",
    "confirm your account security",
    "account login validation",
    "suspicious login detected",
    "phishing attempt detected",
    "your account may be compromised",
    "verify your account credentials",
    "unauthorized access attempt",
    "confirm your account login",
    "urgent account security alert",
    "account security check",
    "validate your login credentials",
    "your account is under review",
    "suspicious activity alert",
    "security measure required",
    "verify your account information",
    "confirm your account details",
    "phishing security alert",
    "account login verification required",
    "suspicious login alert",
    "account security notice",
    "confirm your account access",
    "verify your account access",
    "suspicious login activity detected",
    "phishing security check",
    "urgent account verification",
    "unusual login activity",
    "account security validation",
    "confirm your identity check",
    "your account is being monitored",
    "suspicious access detected",
    "confirm your login security",
    "phishing attempt alert",
    "your account is being investigated",
    "account login validation required",
    "suspicious login validation",
    "phishing activity detected",
    "urgent account security update",
    "account verification alert",
    "verify your account validation",
    "suspicious access attempt",
    "phishing security validation",
    "urgent account review",
    "account validation alert",
    "unauthorized access alert",
    "account security alert",
    "confirm your account review",
    "suspicious login validation alert",
    "phishing security verification",
    "urgent account validation required",
    "urgent action needed",
    "attention required",
    "your account will be closed",
    "your account will be deleted",
    "final notice",
    "account information update",
    "your account needs verification",
    "login attempt detected",
    "unauthorized login detected",
    "account security alert",
    "confirm your account activity",
    "account breach alert",
    "urgent account status",
    "account compromise alert",
    "account security verification",
    "your account is in jeopardy",
    "account in danger of closure",
    "update your account security",
    "confirm your account security",
    "account security notice",
    "verify your account security",
    "account security check",
    "security confirmation required",
    "verify your account status",
    "suspicious login alert",
    "confirm your security check",
    "account security validation",
    "urgent account security check",
    "your account is under investigation",
    "account security update required",
    "your account will be locked",
    "unauthorized access to your account",
    "account access verification",
    "urgent account verification required",
    "account status update",
    "suspicious activity on your account",
    "phishing alert",
    "your account is flagged",
    "suspicious login attempt detected",
    "security breach notification",
    "verify your login credentials",
    "account security check required",
    "your account is being monitored",
    "suspicious login activity detected",
    "phishing attempt detected",
    "urgent security verification",
    "confirm your account validation",
    "suspicious login validation required",
    "your account is compromised",
    "account security validation alert",
    "urgent account access check",
    "suspicious login validation alert",
    "phishing security alert",
    "verify your account investigation",
    "account security investigation",
    "urgent account security validation",
    "confirm your account breach",
    "account compromise alert",
    "phishing security check",
    "verify your account breach alert",
    "urgent account security investigation",
    "suspicious access attempt detected",
    "phishing security validation alert",
    "urgent account security validation required",
    "suspicious login security check",
    "phishing security investigation",
    "your account may be compromised",
    "account security validation required",
    "urgent account security alert",
    "verify your account security check",
    "account security breach detected",
    "account compromised alert",
    "account hacked alert",
    "account info verification",
    "account lock notice",
    "account locked alert",
    "account login validation",
    "account login verification",
    "account password reset",
    "account safety alert",
    "account security alert",
    "account security check",
    "account security confirmation",
    "account security issue",
    "account security notification",
    "account security update",
    "account security verification",
    "account suspension notice",
    "account termination alert",
    "account unauthorized access",
    "alert: account login from new device",
    "change your login credentials",
    "click the link below to verify",
    "confirm your account access",
    "confirm your account activity",
    "confirm your account details",
    "confirm your account login",
    "confirm your account review",
    "confirm your login credentials",
    "confirm your security check",
    "confirm your security validation",
    "confirm your security verification",
    "critical account alert",
    "detecting unauthorized access",
    "emergency account verification",
    "emergency security alert",
    "ensure your account security",
    "final account notice",
    "final warning: account compromise",
    "immediate account verification",
    "important security alert",
    "important security update",
    "important: account verification",
    "important: security check",
    "important: security validation",
    "important: security verification",
    "login attempt from unfamiliar location",
    "login verification required",
    "multiple login attempts detected",
    "password change required",
    "phishing attempt alert",
    "phishing security alert",
    "phishing website detected",
    "protect your account",
    "quick security verification",
    "reactivate your account",
    "recent login attempt alert",
    "recent security activity",
    "reconfirm your account details",
    "reconfirm your login credentials",
    "reconfirm your security check",
    "reconfirm your security validation",
    "reconfirm your security verification",
    "recover your hacked account",
    "recover your compromised account",
    "renew your account security",
    "report suspicious activity",
    "reset your account password",
    "reset your login credentials",
    "reset your password now",
    "security alert notification",
    "security breach detected",
    "security breach notification",
    "security confirmation required",
    "security incident alert",
    "security measure required",
    "security update notification",
    "security validation alert",
    "security verification required",
    "suspicious account activity",
    "suspicious login activity detected",
    "suspicious login attempt alert",
    "suspicious login detected",
    "suspicious login security check",
    "suspicious login validation alert",
    "suspicious security activity",
    "suspicious security alert",
    "suspicious security check",
    "suspicious security notification",
    "suspicious security update",
    "suspicious security verification",
    "suspicious unauthorized access",
    "urgent account access check",
    "urgent account activity verification",
    "urgent account confirmation required",
    "urgent account investigation",
    "urgent account review",
    "urgent account security alert",
    "urgent account security check",
    "urgent account security investigation",
    "urgent account security notice",
    "urgent account security update",
    "urgent account verification",
    "urgent login verification",
    "urgent security alert notification",
    "urgent security check required",
    "urgent security confirmation required",
    "urgent security incident alert",
    "urgent security measure required",
    "urgent security notification",
    "urgent security update",
    "urgent security validation required",
    "urgent security verification",
    "verify your account access",
    "verify your account activity",
    "verify your account details",
    "verify your account login",
    "verify your account review",
    "verify your login credentials",
    "verify your security check",
    "verify your security validation",
    "verify your security verification",
    "warning: account compromise",
    "warning: account security issue",
    "warning: account security notice",
    "warning: account security update",
    "warning: phishing website detected",
    "warning: suspicious account activity",
    "warning: suspicious login attempt",
    "warning: suspicious security activity",
    "warning: urgent account security alert",
    "your account is being monitored",
    "your account is being reviewed",
    "your account is being suspended",
    "your account is in danger",
    "your account is in jeopardy",
    "your account may be compromised",
    "your account may be suspended",
    "your account security is at risk",
    "your account security is compromised",
    "your account security is in danger",
    "your account security is in jeopardy",
    "your account will be blocked",
    "your account will be closed",
    "your account will be deleted",
    "your account will be locked",
    "your account will be suspended",
    "your account will be terminated",
    "your password has been compromised",
    "your password is at risk",
    "your password is compromised",
    "your password is in danger",
    "your password is in jeopardy",
    "your password may be compromised",
    "your password may be in danger",
    "your password may be in jeopardy"
  ]
}
